name: CI

on:
  workflow_call:
    inputs:
      php-extensions:
        description: 'Comma-separated PHP extensions to install.'
        required: false
        type: string
        default: fileinfo

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        php: ['8.3', '8.4', '8.5']

    steps:
      - name: Checkout.
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: ${{ inputs.php-extensions }}
          ini-values: date.timezone='UTC'
          php-version: ${{ matrix.php }}

      - name: Determine composer cache directory.
        shell: bash
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies.
        uses: actions/cache@v6
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Determine Composer root version.
        shell: bash
        run: |
          version="$(composer config extra.branch-alias.dev-main 2>/dev/null || true)"
          if [ -n "$version" ]; then
            echo "COMPOSER_ROOT_VERSION=$version" >> "$GITHUB_ENV"
          fi

      - name: Install dependencies with Composer.
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --colors=always

  psalm:
    name: PHP ${{ matrix.php }}-ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.3', '8.4', '8.5']

    steps:
      - name: Checkout.
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: ${{ inputs.php-extensions }}
          php-version: ${{ matrix.php }}
          tools: cs2pr

      - name: Determine Composer root version.
        shell: bash
        run: |
          version="$(composer config extra.branch-alias.dev-main 2>/dev/null || true)"
          if [ -n "$version" ]; then
            echo "COMPOSER_ROOT_VERSION=$version" >> "$GITHUB_ENV"
          fi

      - name: Install Composer dependencies.
        uses: ramsey/composer-install@v4

      - name: Static analysis.
        run: vendor/bin/psalm --config="psalm.xml" --shepherd --stats --output-format=github --php-version="${{ matrix.php }}"
